version: '3'

services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    restart: always

  hello:
    build: hello
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
    restart: always