---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-depl
  labels:
    app: hello-app
    revision: "6"
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.hello-app: semver:*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: olivernadj/nameko-example-hello:0.0.5
        name: hello
        env:
        - name: RABBIT_HOST
          value: broker-rabbitmq
        - name: RABBIT_MANAGEMENT_PORT
          value: "15672"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: broker-rabbitmq
              key: rabbitmq-password
      restartPolicy: Always
