apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-depl
  namespace: nameko
  labels:
    app: {{ .Chart.Name }}-app
    revision: "{{ .Release.Revision }}"
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.{{ .Chart.Name }}-app: semver:*
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
      - image: olivernadj/nameko-example-hello:0.0.7
        name: {{ .Chart.Name }}
        env:
        - name: RABBIT_HOST
          value: broker-rabbitmq
        - name: RABBIT_MANAGEMENT_PORT
          value: "15672"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: broker-rabbitmq
              key: rabbitmq-password
      restartPolicy: Always